name: Dockpipeline
on: 
  push:
    paths-ignore:
        -  'LICENSE'
        -  'Dockerfile'
        -  'CONTRIBUTING.md'
        -  'README.md'
jobs:
  dockerci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
        
      - name: Build image
        run: docker build -t ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python:rt .
        
      - name: Verify the image 
        run: docker images
      - name: create container
        run: docker run --name python-app -idt -p 8080:8080 ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python:rt
      - name: sleep
        run : sleep 20
      - name: view container
        run: docker ps
      - name: curl output
        run: curl -f http://localhost:8080/
 
      - name: Docker login 
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Push image
        run: docker push ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python:rt  
      - name: container cleanup
        run: docker rm -f python-app
